import type {
  Project,
  Task,
  CalendarEvent,
  Note,
  ChatConversation,
  Secret,
  DashboardStats,
} from '@/types';

// ─── Projects ────────────────────────────────────────────────────────────────
export const mockProjects: Project[] = [
  {
    id: 'p1',
    name: 'Cloud Migration',
    description: 'Migrating legacy infrastructure to AWS with zero downtime',
    color: '#2563eb',
    status: 'active',
    taskCount: 12,
    completedTaskCount: 7,
    createdAt: '2025-11-01T09:00:00Z',
    updatedAt: '2026-02-28T14:22:00Z',
    dueDate: '2026-04-30',
    members: ['demo@ncodx.com'],
    tags: ['aws', 'infrastructure', 'devops'],
  },
  {
    id: 'p2',
    name: 'NCODX Platform',
    description: 'Internal project management and collaboration platform',
    color: '#0d9488',
    status: 'active',
    taskCount: 28,
    completedTaskCount: 15,
    createdAt: '2025-10-15T10:00:00Z',
    updatedAt: '2026-03-04T11:00:00Z',
    dueDate: '2026-06-01',
    members: ['demo@ncodx.com'],
    tags: ['react', 'typescript', 'platform'],
  },
  {
    id: 'p3',
    name: 'Client Portal v2',
    description: 'Redesign and modernize the client-facing portal',
    color: '#7c3aed',
    status: 'active',
    taskCount: 18,
    completedTaskCount: 4,
    createdAt: '2026-01-10T08:00:00Z',
    updatedAt: '2026-03-01T16:00:00Z',
    dueDate: '2026-05-15',
    members: ['demo@ncodx.com'],
    tags: ['ux', 'portal', 'client'],
  },
  {
    id: 'p4',
    name: 'Security Audit 2026',
    description: 'Annual penetration testing and compliance review',
    color: '#dc2626',
    status: 'active',
    taskCount: 9,
    completedTaskCount: 9,
    createdAt: '2026-01-01T09:00:00Z',
    updatedAt: '2026-02-20T15:00:00Z',
    dueDate: '2026-02-28',
    members: ['demo@ncodx.com'],
    tags: ['security', 'compliance', 'audit'],
  },
  {
    id: 'p5',
    name: 'AI Integration Suite',
    description: 'Integrate LLM capabilities across client products',
    color: '#d97706',
    status: 'active',
    taskCount: 22,
    completedTaskCount: 6,
    createdAt: '2026-02-01T09:00:00Z',
    updatedAt: '2026-03-03T10:00:00Z',
    dueDate: '2026-07-01',
    members: ['demo@ncodx.com'],
    tags: ['ai', 'llm', 'integration'],
  },
  {
    id: 'p6',
    name: 'DevOps Pipeline Overhaul',
    description: 'Rebuild CI/CD pipelines with GitOps approach',
    color: '#059669',
    status: 'paused',
    taskCount: 14,
    completedTaskCount: 3,
    createdAt: '2025-12-01T09:00:00Z',
    updatedAt: '2026-01-15T12:00:00Z',
    dueDate: '2026-05-30',
    members: ['demo@ncodx.com'],
    tags: ['devops', 'cicd', 'gitops'],
  },
];

// ─── Tasks ───────────────────────────────────────────────────────────────────
export const mockTasks: Task[] = [
  {
    id: 't1',
    title: 'Set up VPC and subnets in eu-west-3',
    description: 'Create private/public subnets, route tables, NAT gateway',
    status: 'done',
    priority: 'high',
    projectId: 'p1',
    projectName: 'Cloud Migration',
    projectColor: '#2563eb',
    dueDate: '2026-02-15',
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-02-14T16:00:00Z',
    tags: ['aws', 'networking'],
  },
  {
    id: 't2',
    title: 'Configure RDS PostgreSQL cluster',
    description: 'Set up multi-AZ RDS with read replicas and automated backups',
    status: 'in_progress',
    priority: 'high',
    projectId: 'p1',
    projectName: 'Cloud Migration',
    projectColor: '#2563eb',
    dueDate: '2026-03-15',
    createdAt: '2026-01-15T09:00:00Z',
    updatedAt: '2026-03-01T14:00:00Z',
    tags: ['aws', 'database'],
  },
  {
    id: 't3',
    title: 'Implement Kanban board drag & drop',
    description: 'Use @dnd-kit to create fully interactive kanban columns',
    status: 'in_progress',
    priority: 'medium',
    projectId: 'p2',
    projectName: 'NCODX Platform',
    projectColor: '#0d9488',
    dueDate: '2026-03-10',
    createdAt: '2026-02-20T11:00:00Z',
    updatedAt: '2026-03-04T09:00:00Z',
    tags: ['react', 'ui'],
  },
  {
    id: 't4',
    title: 'Design new dashboard UI mockups',
    description: 'Create Figma mockups for the updated dashboard layout',
    status: 'review',
    priority: 'medium',
    projectId: 'p3',
    projectName: 'Client Portal v2',
    projectColor: '#7c3aed',
    dueDate: '2026-03-08',
    createdAt: '2026-02-01T10:00:00Z',
    updatedAt: '2026-03-03T15:00:00Z',
    tags: ['design', 'ux'],
  },
  {
    id: 't5',
    title: 'Write API documentation',
    description: 'Document all REST endpoints with OpenAPI 3.0 spec',
    status: 'todo',
    priority: 'low',
    projectId: 'p2',
    projectName: 'NCODX Platform',
    projectColor: '#0d9488',
    dueDate: '2026-03-20',
    createdAt: '2026-02-25T08:00:00Z',
    updatedAt: '2026-02-25T08:00:00Z',
    tags: ['documentation', 'api'],
  },
  {
    id: 't6',
    title: 'Integrate GPT-4 for code review assistant',
    description: 'Build LLM-powered code review suggestions in PR workflow',
    status: 'todo',
    priority: 'urgent',
    projectId: 'p5',
    projectName: 'AI Integration Suite',
    projectColor: '#d97706',
    dueDate: '2026-03-25',
    createdAt: '2026-02-28T09:00:00Z',
    updatedAt: '2026-02-28T09:00:00Z',
    tags: ['ai', 'gpt', 'devtools'],
  },
  {
    id: 't7',
    title: 'Set up EKS cluster with Terraform',
    description: 'Kubernetes cluster with auto-scaling node groups',
    status: 'todo',
    priority: 'high',
    projectId: 'p6',
    projectName: 'DevOps Pipeline Overhaul',
    projectColor: '#059669',
    dueDate: '2026-04-01',
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-03-01T10:00:00Z',
    tags: ['k8s', 'terraform'],
  },
  {
    id: 't8',
    title: 'Implement OAuth2 for client portal',
    description: 'Add Google and Microsoft SSO to the client login flow',
    status: 'review',
    priority: 'high',
    projectId: 'p3',
    projectName: 'Client Portal v2',
    projectColor: '#7c3aed',
    dueDate: '2026-03-12',
    createdAt: '2026-02-10T11:00:00Z',
    updatedAt: '2026-03-02T17:00:00Z',
    tags: ['auth', 'oauth', 'security'],
  },
];

// ─── Calendar Events ──────────────────────────────────────────────────────────
const today = new Date();
const y = today.getFullYear();
const m = today.getMonth();

export const mockCalendarEvents: CalendarEvent[] = [
  {
    id: 'e1',
    title: 'Sprint Planning',
    start: new Date(y, m, today.getDate() + 1, 10, 0),
    end: new Date(y, m, today.getDate() + 1, 11, 30),
    description: 'Q1 sprint planning session',
    source: 'internal',
    color: '#2563eb',
  },
  {
    id: 'e2',
    title: 'Client Review — Cloud Migration',
    start: new Date(y, m, today.getDate() + 2, 15, 0),
    end: new Date(y, m, today.getDate() + 2, 16, 0),
    description: 'Demo progress to client team',
    source: 'google',
    color: '#dc2626',
  },
  {
    id: 'e3',
    title: 'Team Standup',
    start: new Date(y, m, today.getDate(), 9, 30),
    end: new Date(y, m, today.getDate(), 9, 45),
    description: 'Daily sync',
    source: 'internal',
    color: '#0d9488',
  },
  {
    id: 'e4',
    title: 'Security Training',
    start: new Date(y, m, today.getDate() + 4, 14, 0),
    end: new Date(y, m, today.getDate() + 4, 17, 0),
    description: 'Annual cybersecurity awareness training',
    source: 'outlook',
    color: '#7c3aed',
  },
  {
    id: 'e5',
    title: 'Product Roadmap Review',
    start: new Date(y, m, today.getDate() + 7, 11, 0),
    end: new Date(y, m, today.getDate() + 7, 12, 30),
    description: 'Q2 roadmap alignment with stakeholders',
    source: 'google',
    color: '#d97706',
  },
  {
    id: 'e6',
    title: 'Deploy to Production',
    start: new Date(y, m, today.getDate() + 3, 20, 0),
    end: new Date(y, m, today.getDate() + 3, 22, 0),
    description: 'Cloud Migration phase 1 deployment',
    source: 'internal',
    color: '#059669',
  },
];

// ─── Notes ────────────────────────────────────────────────────────────────────
export const mockNotes: Note[] = [
  {
    id: 'n1',
    title: 'Architecture Decision',
    content: 'Use OAC instead of OAI for new CloudFront distributions. OAI is legacy.',
    color: 'yellow',
    pinned: true,
    posX: 80,
    posY: 80,
    createdAt: '2026-02-10T10:00:00Z',
    updatedAt: '2026-02-10T10:00:00Z',
  },
  {
    id: 'n2',
    title: 'Client Meeting Notes',
    content: 'TechCorp wants Kubernetes by Q2. Budget approved. Escalate to Miguel.',
    color: 'pink',
    pinned: false,
    posX: 320,
    posY: 80,
    createdAt: '2026-02-15T14:00:00Z',
    updatedAt: '2026-02-15T14:00:00Z',
  },
  {
    id: 'n3',
    title: 'API Keys to rotate',
    content: '- OpenAI key (expires Mar 15)\n- Stripe webhook key\n- AWS access key prod',
    color: 'green',
    pinned: true,
    posX: 560,
    posY: 80,
    createdAt: '2026-02-20T09:00:00Z',
    updatedAt: '2026-03-01T11:00:00Z',
  },
  {
    id: 'n4',
    title: 'Tech Debt',
    content: 'Migrate from CRA to Vite. Update React Query v4→v5. Remove lodash deps.',
    color: 'blue',
    pinned: false,
    posX: 80,
    posY: 300,
    createdAt: '2026-02-25T15:00:00Z',
    updatedAt: '2026-02-25T15:00:00Z',
  },
  {
    id: 'n5',
    title: 'Ideas',
    content: 'Add AI-powered PR reviews. Auto-generate release notes. Voice commands?',
    color: 'orange',
    pinned: false,
    posX: 320,
    posY: 300,
    createdAt: '2026-03-01T12:00:00Z',
    updatedAt: '2026-03-01T12:00:00Z',
  },
];

// ─── Chat Conversations ───────────────────────────────────────────────────────
export const mockConversations: ChatConversation[] = [
  {
    id: 'c1',
    title: 'Cloud Architecture Review',
    createdAt: '2026-03-04T10:00:00Z',
    updatedAt: '2026-03-04T10:30:00Z',
    messages: [
      {
        id: 'm1',
        role: 'user',
        content: 'What are the best practices for a multi-region AWS architecture?',
        timestamp: '2026-03-04T10:00:00Z',
      },
      {
        id: 'm2',
        role: 'assistant',
        content:
          'For a resilient multi-region AWS architecture, consider these key practices:\n\n1. **Active-Active vs Active-Passive**: Choose based on your RTO/RPO requirements\n2. **Global services**: Use Route53 with latency/failover routing, CloudFront for CDN\n3. **Data replication**: DynamoDB Global Tables, RDS cross-region replicas, S3 CRR\n4. **Stateless services**: Design workloads to be stateless for easy failover\n5. **IaC**: Use Terraform modules per region with shared state in S3+DynamoDB\n\nWhich aspect would you like to dive deeper into?',
        timestamp: '2026-03-04T10:01:00Z',
      },
    ],
  },
  {
    id: 'c2',
    title: 'TypeScript help',
    createdAt: '2026-03-03T15:00:00Z',
    updatedAt: '2026-03-03T15:20:00Z',
    messages: [
      {
        id: 'm3',
        role: 'user',
        content: 'How do I type a generic API response in TypeScript?',
        timestamp: '2026-03-03T15:00:00Z',
      },
      {
        id: 'm4',
        role: 'assistant',
        content:
          "Here's a clean pattern for typed API responses:\n\n```typescript\ninterface ApiResponse<T> {\n  data: T;\n  error: string | null;\n  status: number;\n  meta?: {\n    page: number;\n    total: number;\n  };\n}\n\nasync function fetchUser(id: string): Promise<ApiResponse<User>> {\n  const res = await fetch(`/api/users/${id}`);\n  return res.json();\n}\n```\n\nThis gives you full type safety throughout your app.",
        timestamp: '2026-03-03T15:01:00Z',
      },
    ],
  },
];

// ─── Secrets ─────────────────────────────────────────────────────────────────
export const mockSecrets: Secret[] = [
  {
    id: 's1',
    name: 'OpenAI API Key',
    value: 'sk-proj-abc123def456ghi789jkl012mno345pqr678stu901vwx234',
    category: 'api_key',
    description: 'Production OpenAI key for AI features',
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-02-01T10:00:00Z',
  },
  {
    id: 's2',
    name: 'GitHub PAT — CI/CD',
    value: 'ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    category: 'token',
    description: 'Personal access token for GitHub Actions workflows',
    createdAt: '2026-01-01T10:00:00Z',
    updatedAt: '2026-01-01T10:00:00Z',
  },
  {
    id: 's3',
    name: 'AWS Root Account Password',
    value: 'Sup3rS3cur3P@ssw0rd!2026',
    category: 'password',
    description: 'Emergency root access only — store in vault!',
    createdAt: '2025-06-01T10:00:00Z',
    updatedAt: '2026-01-01T10:00:00Z',
  },
  {
    id: 's4',
    name: 'Stripe Webhook Secret',
    value: 'whsec_abcdefghijklmnopqrstuvwxyz123456',
    category: 'api_key',
    description: 'Stripe webhook signature verification',
    createdAt: '2026-02-10T10:00:00Z',
    updatedAt: '2026-02-10T10:00:00Z',
  },
  {
    id: 's5',
    name: 'PostgreSQL prod password',
    value: 'pg_prod_secr3t_2026!!',
    category: 'password',
    description: 'Production RDS PostgreSQL master password',
    createdAt: '2025-11-01T10:00:00Z',
    updatedAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 's6',
    name: 'Datadog API Key',
    value: 'dd_api_1a2b3c4d5e6f7g8h9i0j',
    category: 'api_key',
    description: 'Observability and monitoring',
    createdAt: '2026-01-20T10:00:00Z',
    updatedAt: '2026-01-20T10:00:00Z',
  },
];

// ─── Dashboard Stats ──────────────────────────────────────────────────────────
export const mockDashboardStats: DashboardStats = {
  totalTasks: mockTasks.length,
  completedToday: 3,
  pending: mockTasks.filter((t) => t.status === 'todo').length,
  activeProjects: mockProjects.filter((p) => p.status === 'active').length,
};
